db:
  name: root
  password: fat-chain-root-password
  ip: 54.254.77.93
  port: 3306
  btc_database: btc_block_data
  eth_database: eth_block_data
  bsc_database: bsc_block_data
  hui_database: block_data_test
  tron_database: TronBlock

MonitorTime:
  BTC: 1200
  BSC: 4
  ETH: 20
  HUI: 6
  TRON: 5
  query_interval: 2

log:
  stdout:
    enable: true
    level: 5
  file:
    enable: false
    path: "./log/app.log"
    level: 4
  kafka:
    enable: false
    topic: "Hui-test"
    kafka_servers:
      - "kafka-1.Hui.com:9092"
      - "kafka-2.Hui.com:9092"
      - "kafka-3.Hui.com:9092"
    level: 3

