db:
  name: root
  password: csquan253905
  ip: 127.0.0.1
  port: 3306
  btc_database: btc_block_test
  eth_database: block_eth_test
  bsc_database: block_data_test
  hui_database: block_data_test
  tron_database: TronBlock

MonitorTime:
  BTC: 1200
  BSC: 4
  ETH: 20
  HUI: 6
  TRON: 5
  query_interval: 2

log:
  stdout:
    enable: true
    level: 5
  file:
    enable: true
    path: "./log/app.log"
    level: 4
  kafka:
    enable: false
    topic: "Hui-test"
    kafka_servers:
      - "kafka-1.Hui.com:9092"
      - "kafka-2.Hui.com:9092"
      - "kafka-3.Hui.com:9092"
    level: 3

